const emoji = {
  EXPRESSION_ICON: [
    { code: 'R.mipmap.e40a', name: 'e40a' },
    { code: 'R.mipmap.e402', name: 'e402' },
    { code: 'R.mipmap.e417', name: 'e417' },
    { code: 'R.mipmap.e105', name: 'e105' },
    { code: 'R.mipmap.e409', name: 'e409' },
    { code: 'R.mipmap.e411', name: 'e411' },
    { code: 'R.mipmap.e404', name: 'e404' },
    { code: 'R.mipmap.e405', name: 'e405' },
    { code: 'R.mipmap.e40e', name: 'e40e' },
    { code: 'R.mipmap.e403', name: 'e403' },
    { code: 'R.mipmap.e407', name: 'e407' },
    { code: 'R.mipmap.e418', name: 'e418' },
    { code: 'R.mipmap.e416', name: 'e416' },
    { code: 'R.mipmap.e401', name: 'e401' },
    { code: 'R.mipmap.e40b', name: 'e40b' },
    { code: 'R.mipmap.e40f', name: 'e40f' },
    { code: 'R.mipmap.e107', name: 'e107' },
    { code: 'R.mipmap.e410', name: 'e410' },
    { code: 'R.mipmap.e40d', name: 'e40d' },
    { code: 'R.mipmap.e40c', name: 'e40c' },
    { code: 'R.mipmap.e22e', name: 'e22e' },
    { code: 'R.mipmap.e22f', name: 'e22f' },
    { code: 'R.mipmap.e230', name: 'e230' },
    { code: 'R.mipmap.e231', name: 'e231' }
  ],
  CUSTOM_ICON: [
    { code: 'R.mipmap.c_weixiao-]', name: '[微笑]', english: '[Smile]' },
    { code: 'R.mipmap.c_se-]', name: '[色]', english: '[Drool]' },
    { code: 'R.mipmap.c_deyi-]', name: '[得意]', english: '[Smug]' },
    { code: 'R.mipmap.c_liulei-]', name: '[流泪]', english: '[Tears]' },
    { code: 'R.mipmap.c_haixiu-]', name: '[害羞]', english: '[Shy]' },
    { code: 'R.mipmap.c_bizui-]', name: '[闭嘴]', english: '[Slience]' },
    { code: 'R.mipmap.c_shui-]', name: '[睡]', english: '[Sleep]' },
    { code: 'R.mipmap.c_ganga-]', name: '[尴尬]', english: '[Awkward]' },
    { code: 'R.mipmap.c_fanu-]', name: '[发怒]', english: '[Angry]' },
    { code: 'R.mipmap.c_tiaopi-]', name: '[调皮]', english: '[Naughty]' },
    { code: 'R.mipmap.c_ciya-]', name: '[呲牙]', english: '[Grin]' },
    { code: 'R.mipmap.c_jingya-]', name: '[惊讶]', english: '[Surprise]' },
    { code: 'R.mipmap.c_zhuakuang-]', name: '[抓狂]', english: '[Scream]' },
    { code: 'R.mipmap.c_touxiao-]', name: '[偷笑]', english: '[Titter]' },
    { code: 'R.mipmap.c_baiyan-]', name: '[白眼]', english: '[Slight]' },
    { code: 'R.mipmap.c_zuohengheng-]', name: '[左哼哼]', english: '[BahLeft]' },
    { code: 'R.mipmap.c_liuhan-]', name: '[流汗]', english: '[Speechless]' },
    { code: 'R.mipmap.c_yiwen-]', name: '[疑问]', english: '[Question]' },
    { code: 'R.mipmap.c_bugaoxing-]', name: '[不高兴]', english: '[Unhappy]' },
    { code: 'R.mipmap.c_yun-]', name: '[晕]', english: '[Dizzy]' },
    { code: 'R.mipmap.c_fengle-]', name: '[疯了]', english: '[Crazy]' },
    { code: 'R.mipmap.c_qiaoda-]', name: '[敲打]', english: '[Hammer]' },
    { code: 'R.mipmap.c_shuai-]', name: '[衰]', english: '[Unlucky]' },
    { code: 'R.mipmap.c_zaijian-]', name: '[再见]', english: '[Bye]' },
    { code: 'R.mipmap.c_koubi-]', name: '[抠鼻]', english: '[NosePick]' },
    { code: 'R.mipmap.c_guzhang-]', name: '[鼓掌]', english: '[Applaud]' },
    { code: 'R.mipmap.c_youhengheng-]', name: '[右哼哼]', english: '[BahRight]' },
    { code: 'R.mipmap.c_bishi-]', name: '[鄙视]', english: '[Disdain]' },
    { code: 'R.mipmap.c_weiqu-]', name: '[委屈]', english: '[Grievance]' },
    { code: 'R.mipmap.c_yinxian-]', name: '[阴险]', english: '[Sly]' },
    { code: 'R.mipmap.c_qinqin-]', name: '[亲亲]', english: '[Kiss]' },
    { code: 'R.mipmap.c_kelian-]', name: '[可怜]', english: '[Pitiful]' },
    { code: 'R.mipmap.c_aida-]', name: '[挨打]', english: '[Beating]' },
    { code: 'R.mipmap.c_aoman-]', name: '[傲慢]', english: '[Arrogance]' },
    { code: 'R.mipmap.c_buxie-]', name: '[不屑]', english: '[Scorn]' },
    { code: 'R.mipmap.c_daxiao-]', name: '[大笑]', english: '[Laughter]' },
    { code: 'R.mipmap.c_heng-]', name: '[哼]', english: '[Hummed]' },
    { code: 'R.mipmap.c_huachi-]', name: '[花痴]', english: '[Anthomaniac]' },
    { code: 'R.mipmap.c_huaixiao-]', name: '[坏笑]', english: '[BadSmile]' },
    { code: 'R.mipmap.c_ku-]', name: '[哭]', english: '[Cry]' },
    { code: 'R.mipmap.c_kun-]', name: '[困]', english: '[Tired]' },
    { code: 'R.mipmap.c_lenghan-]', name: '[冷汗]', english: '[ColdSweat]' },
    { code: 'R.mipmap.c_nanguo-]', name: '[难过]', english: '[Sad]' },
    { code: 'R.mipmap.c_nu-]', name: '[怒]', english: '[Rage]' },
    { code: 'R.mipmap.c_qiexiao-]', name: '[窃笑]', english: '[Snickered]' },
    { code: 'R.mipmap.c_xia-]', name: '[吓]', english: '[Threaten]' },
    { code: 'R.mipmap.c_xu-]', name: '[嘘]', english: '[Sh]' },
    { code: 'R.mipmap.c_zhemo-]', name: '[折磨]', english: '[Torment]' }
  ]
}

// 自定义表情
export default emoji
